version: '3.8'

services:
  app:
    build: .
    container_name: bus-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/app
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
